remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
title: "What Types of Recipes Are Healthier?"
description: "A data science investigation into protein and carbohydrate content across Food.com recipe categories."
author: "Chau Nguyen"
